# Site settings
title: Bassam Saeed
email: bassam.saeed@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Personal dev blog.
baseurl: # the subpath of your site, e.g. /blog/
url: "bassamsaeed.ca" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: kalq

# Build settings
markdown: kramdown
